travis:
  secure:
    BINSTAR_TOKEN: oCM0LPbXJ2TI473c8qitbPxB45sV/fc4xxYtHQH5hU7CNx6DznC9hFHNv67RsonoJXbcaaL2fzaq1kj7lX/sd34sb502Slwb+IX1NwqnrrUIBB8XuN2v8qynnvmh8T2GNEIecygzILX3iPpPZqlLVq8FmZhPYICI7Tia2I5ppoXsOh3/ZiWM4pw7lZod57QpgxJ6g8K8nWZmIvzAzWSajsH99JKsH9TGMJaTo1vSy9NRWkpBzivEWMmr10+BoZYQRPDAr/bmgiq98dDnpfDeek5UVDan8yQljpcz0wLUYwAp2POeF7ESIO2EZ80YhK6ktsw+F+TxHfuY8efDXBlf0w5juQCxufebZljFz7kvwBbUa8DGD6vH8D6gnVkT7WxK+hOs3yuZDSnFLVJULmAORxjmXD85QJxov0ENSfNFkqRPbbOM8wJdOgQPCeji0mHEGBoym5hFhdrCmS7yAfKv2K7ueI0Epgt5EAYXV46TeWbXAHxhCIDC6Bp5Sb8ynF68aJwWHUYEqUA0aQ8wd9UNaf3WQTnoyOrY7+P6yYJOEA/5B6QhuS9CSu5txbVEqCwnpvT3YT4TIGYtfhqsSu5zmGKg8i75AiiyEvlfEY/elce3qwnxwtpKw6BlpZgbockp8QvY4RNL2zx3yHsh5wNH+yTXvjaDMzDBb+RN0S9wThA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
